name: Publish Website

on:
  push:
    branches: # triggers on any push to master
    - master
  schedule: # also triggers once per week
    - cron: 0 0 * * 1

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: node --version
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: parcel build index.html --public-url ./
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
